/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadExp */

#ifndef _Included_ThreadExp
#define _Included_ThreadExp
#ifdef __cplusplus
extern "C" {
#endif
#undef ThreadExp_MIN_PRIORITY
#define ThreadExp_MIN_PRIORITY 1L
#undef ThreadExp_NORM_PRIORITY
#define ThreadExp_NORM_PRIORITY 5L
#undef ThreadExp_MAX_PRIORITY
#define ThreadExp_MAX_PRIORITY 10L
/*
 * Class:     ThreadExp
 * Method:    sleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ThreadExp_sleep
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
