name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker run -p 8080:80 -d --rm --name my_nginx3 nginx 
    - name: check
      run: curl -v http://localhost:8080
